# .github/workflows/build.yml
name: Build Mod # Your preferred workflow name

on: [push, pull_request] # Triggers on pushes and pull requests

jobs:
  buildJar: # Your preferred job name
    runs-on: ubuntu-latest # Use a Linux environment for the build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4 # Action to check out your code from the repo. Updated to v4 for consistency.

    - name: Set up JDK 17
      # IMPORTANT: Updated to v4 to fix the download error
      uses: actions/setup-java@v4
      with:
        java-version: '17' # Mindustry typically requires JDK 17
        distribution: 'temurin' # A common OpenJDK distribution
        cache: 'gradle' # Cache Gradle dependencies to speed up builds

    - name: Install Android SDK # NEW: Essential for './gradlew deploy'
      run: |
        # Create a directory for the Android SDK
        mkdir -p "${{ runner.temp }}/android-sdk/cmdline-tools"
        # Download and unzip the command-line tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-8583979_latest.zip -O android-cmdline-tools.zip
        unzip -q android-cmdline-tools.zip -d "${{ runner.temp }}/android-sdk/cmdline-tools/latest"
        # Set ANDROID_HOME environment variable for this job
        echo "ANDROID_HOME=${{ runner.temp }}/android-sdk" >> $GITHUB_ENV
        # Install platform and build-tools (using a common API level like 33 or 34)
        yes | "${{ runner.temp }}/android-sdk/cmdline-tools/latest/bin/sdkmanager" --licenses
        "${{ runner.temp }}/android-sdk/cmdline-tools/latest/bin/sdkmanager" "platforms;android-33" "build-tools;33.0.0"

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew # Make the Gradle wrapper executable

    - name: Build mod jar (Desktop & Android)
      # Using 'deploy' as per your original workflow, which typically builds a cross-platform JAR
      run: ./gradlew deploy

    - name: Upload built jar file
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }} # Uses your repo name as artifact name
        path: build/libs/${{ github.event.repository.name }}.jar # Assumes the JAR is named after your repo
        # If your build produces a different name (e.g., 'yourmodname-dex.jar'), adjust the path accordingly.
